import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {JSDOM,VirtualConsole} from 'jsdom';
import {randomUUID} from 'node:crypto';
import worker from '../worker/index.js';
import {database} from '../server/d1.mjs';
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,20))}throw new Error('Client condition timed out')};
function client(env){const errors=[];const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e)});const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'https://test.example/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};w.crypto.randomUUID=randomUUID;w.speechSynthesis={cancel(){},speak(){},pause(){},resume(){}};w.SpeechSynthesisUtterance=function(text){this.text=text};w.fetch=async(url,options={})=>{const headers=new Headers(options.headers);headers.set('oai-authenticated-user-id','ui-owner');headers.set('origin','https://test.example');return worker.fetch(new Request(new URL(url,w.location.href),{...options,headers}),env)};const asset=readdirSync(new URL('../dist/client/assets/',import.meta.url)).find(x=>x.endsWith('.js'));w.eval(readFileSync(new URL('../dist/client/assets/'+asset,import.meta.url),'utf8'));return {dom,w,errors,text:()=>w.document.body.textContent,button:text=>[...w.document.querySelectorAll('button')].find(b=>b.textContent.trim()===text),input:(selector,value)=>{const node=w.document.querySelector(selector);const prototype=node.tagName==='TEXTAREA'?w.HTMLTextAreaElement.prototype:w.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value').set.call(node,value);node.dispatchEvent(new w.Event('input',{bubbles:true}));node.dispatchEvent(new w.Event('change',{bubbles:true}))}}}
test('rendered client connects practice, help, resume, debrief, review and growth',async()=>{let turns=0;const env={DB:database(),CODEX_ACCOUNT:async()=>({account:{type:'chatgpt'}}),CODEX_COMPLETE:async messages=>{const {task,input}=JSON.parse(messages[1].content);if(task==='tutor')return {reply:++turns===1?'What would you like to order?':'Would you like anything to drink?',hint:'说明需求',phrases:[]};if(task==='help')return {reply:'先说 I would like，然后加食物名称。',phrases:['I would like…']};if(task==='assess')return {summary:'You explained what you wanted.',items:[{original:'I want chicken.',issue:'可以更礼貌',correct:'I would like chicken.',natural:'I would like some chicken, please.',executive:'Could I have the chicken, please?',reminder:'Practice the phrase smoothly.',similar:['I would like some water.'],category:'style',review:true}],nextFocus:['Next time try without hints.'],passed:false,quote:'I want chicken.',reason:'Used coaching help.'};if(task==='retrieve')return {passed:true,reply:'意思清楚。',natural:'I would like some chicken, please.',reason:'Appropriate request.'};throw new Error('Unexpected task '+task)}};
 let c=client(env);try{await wait(()=>c.button('开始带我练')&&!c.button('开始带我练').disabled);c.button('开始带我练').click();await wait(()=>c.text().includes('What would you like to order?'));c.input('textarea[aria-label="你的回答"]','I want chicken.');c.w.document.querySelector('form.composer').dispatchEvent(new c.w.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>c.text().includes('Would you like anything to drink?'));c.button('给我提示').click();await wait(()=>c.text().includes('先说 I would like'));assert.equal(c.errors.length,0);c.dom.window.close();c=client(env);await wait(()=>c.text().includes('接着上次聊'));const resume=[...c.w.document.querySelectorAll('button.listRow')][0];resume.click();await wait(()=>c.text().includes('I want chicken.'));c.button('结束并复盘 →').click();await wait(()=>c.text().includes('每一次开口，都留下进步。'));c.button('加入复习').click();await wait(()=>c.text().includes('已加入复习'));c.button('复习').click();await wait(()=>c.text().includes('I would like chicken.'));[...c.w.document.querySelectorAll('button.listRow')][0].click();await wait(()=>c.w.document.querySelector('textarea[aria-label="复习答案"]'));c.input('textarea[aria-label="复习答案"]','Could I have chicken, please?');c.button('检查我的表达').click();await wait(()=>c.text().includes('这次表达达到了目标'));c.button('成长').click();await wait(()=>c.text().includes('尚未评估'));assert.equal(c.errors.length,0);}finally{c.dom.window.close();env.DB.sqlite.close()}});
