import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {database} from './d1.mjs';
import {CodexBridge} from './codex.mjs';
import {checkPassword,issueSession,validSession} from './auth.mjs';
import worker from '../worker/index.js';
const origin=process.env.APP_ORIGIN,secret=process.env.SESSION_SECRET,passwordHash=process.env.OWNER_PASSWORD_HASH;
if(!origin||!secret||secret.length<32||!passwordHash||!process.env.AI_ENCRYPTION_KEY)throw new Error('APP_ORIGIN, SESSION_SECRET (32+ chars), OWNER_PASSWORD_HASH and AI_ENCRYPTION_KEY are required.');
const publicOrigin=new URL(origin);if(publicOrigin.protocol!=='https:'&&publicOrigin.hostname!=='localhost')throw new Error('Production requires HTTPS.');
const directory=resolve(process.env.DATA_DIR||'./private-data');await mkdir(directory,{recursive:true,mode:0o700});
const DB=database(resolve(directory,'learning.sqlite'));const bridge=new CodexBridge({home:resolve(directory,'codex'),workspace:resolve(directory,'empty-workspace')});
const root=resolve('dist/client');const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const assets={async fetch(request){const path=decodeURIComponent(new URL(request.url).pathname);const file=resolve(root,'.'+path);if(!file.startsWith(root+'/'))return new Response('Not found',{status:404});try{return new Response(await readFile(file),{headers:{'content-type':mime[extname(file)]||'application/octet-stream'}})}catch{return new Response('Not found',{status:404})}}};
const codexEnabled=process.env.MODEL_BACKEND!=='api';const env={DB,ASSETS:assets,AI_ENCRYPTION_KEY:process.env.AI_ENCRYPTION_KEY,...(codexEnabled?{CODEX_COMPLETE:m=>bridge.complete(m),CODEX_ACCOUNT:()=>bridge.account()}: {})};
const loginPage=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Global Copilot · 登录</title><style>body{font:16px/1.7 system-ui;background:#f7f8f5;color:#20362a;max-width:400px;margin:12vh auto;padding:24px}input,button{box-sizing:border-box;width:100%;padding:14px;margin:10px 0;border:1px solid #dce4dd;border-radius:8px;font:inherit}button{background:#17674e;color:white}small{color:#65796d}</style><h1>Global Copilot</h1><p>进入你的私人英语陪练空间。</p><form id="login"><input id="password" type="password" autocomplete="current-password" placeholder="工作台访问密码" required><button>登录工作台</button></form><p id="error" role="alert"></p><small>进入后可以连接你的 ChatGPT 账号。</small><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();const r=await fetch('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:document.querySelector('input').value})});if(r.ok)location.href='/';else document.querySelector('#error').textContent='登录失败，请检查密码，或稍后再试。'}</script></html>`;
const attempts=new Map();function json(x,status=200){return Response.json(x,{status})}
const server=createServer(async(req,res)=>{let response;try{const url=new URL(req.url,origin);if(url.origin!==publicOrigin.origin)throw new Error('Invalid host');const write=!['GET','HEAD'].includes(req.method);if(write&&req.headers.origin!==publicOrigin.origin){response=json({error:'请求来源无效'},403)}else{let buffer='';for await(const chunk of req){buffer+=chunk;if(Buffer.byteLength(buffer)>750000)throw Object.assign(new Error('请求过大'),{status:413})}
 const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('copilot_session='))?.slice(16);const signedIn=validSession(token||'',secret);
 if(url.pathname==='/auth/login'&&req.method==='POST'){const ip=req.socket.remoteAddress;const now=Date.now();for(const [k,v] of attempts)if(now-v.since>900000)attempts.delete(k);const a=attempts.get(ip)||{count:0,since:now};a.count++;attempts.set(ip,a);if(a.count>10)response=json({error:'尝试过多，请 15 分钟后重试'},429);else if(checkPassword(String(JSON.parse(buffer).password||'').slice(0,500),passwordHash)){attempts.delete(ip);response=json({ok:true});response.headers.set('set-cookie',`copilot_session=${issueSession(secret)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${publicOrigin.protocol==='https:'?'; Secure':''}`)}else response=json({error:'密码错误'},401)
 }else if(!signedIn){response=url.pathname.startsWith('/api/')?json({error:'请重新登录工作台'},401):new Response(loginPage,{headers:{'content-type':'text/html; charset=utf-8'}})
 }else if(url.pathname==='/auth/logout'&&req.method==='POST'){response=json({ok:true});response.headers.set('set-cookie','copilot_session=; Max-Age=0; HttpOnly; SameSite=Strict; Path=/')
 }else if(url.pathname==='/api/auth/codex/start'&&req.method==='POST'&&codexEnabled)response=json(await bridge.login());
 else if(url.pathname==='/api/auth/codex/logout'&&req.method==='POST'&&codexEnabled)response=json(await bridge.logout());
 else {const headers=new Headers();for(const [k,v] of Object.entries(req.headers))if(v&&!k.toLowerCase().startsWith('oai-')&&!['host','content-length'].includes(k.toLowerCase()))headers.set(k,Array.isArray(v)?v.join(','):v);headers.set('oai-authenticated-user-id','private-owner');response=await worker.fetch(new Request(url,{method:req.method,headers,...(write?{body:buffer}:{})}),env)}
 }}catch(e){response=json({error:e.status?e.message:'服务暂时不可用，请重试。'},e.status||503)}
 response.headers.set('cache-control','private, no-store');response.headers.set('x-content-type-options','nosniff');response.headers.set('x-frame-options','DENY');response.headers.set('referrer-policy','same-origin');res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))});
server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('Global Copilot server ready'));process.on('SIGTERM',()=>{bridge.close();server.close(()=>process.exit(0))});
