export const categories=['Stablecoin','Payments','Banking','Web3','Blockchain','Compliance','KYC/KYB','AML','Treasury','Settlement','Clearing','FX','Liquidity','Custody','Wallet','On-ramp / Off-ramp','Cross-border payments','Licensing','Partnership','JV','Fundraising','Negotiation'];
const raw=[
['Stablecoin','Redemption','赎回','Convert a token back into its underlying currency.','按发行方约定将代币兑换为法币；资格、费用和到账时间依条款而定。','redemption window; redeem at par','What are your redemption terms and settlement timelines?'],
['Payments','Payment rails','支付通道','The networks that move money.','银行、卡组织或本地支付系统用于传递支付指令和资金的网络。','local payment rails; access payment rails','Which local payment rails can your platform support?'],
['Banking','Correspondent banking','代理银行业务','One bank provides services for another.','银行通过代理关系获得其他市场或币种的支付服务。','correspondent relationship; banking partner','Do you have a banking partner for this corridor?'],
['Web3','Interoperability','互操作性','Different systems working together.','网络、钱包和应用之间交换信息或资产的能力。','cross-chain interoperability','How do you handle interoperability across networks?'],
['Blockchain','Finality','最终性','When a transaction is considered irreversible.','交易达到约定不可逆状态；具体判断取决于网络设计。','transaction finality; settlement finality','How do you determine transaction finality?'],
['Compliance','Regulatory requirements','监管要求','Rules a business must follow.','具体业务、实体和司法辖区适用的义务，需由合规人员确认。','meet regulatory requirements','Which requirements apply to the proposed pilot?'],
['KYC/KYB','Beneficial owner','实际受益所有人','A person who ultimately owns or controls a business.','客户尽调需要识别的最终拥有或控制企业的自然人。','identify beneficial owners','What documents do you need to verify beneficial owners?'],
['AML','Transaction monitoring','交易监测','Reviewing transactions for unusual activity.','使用风险规则和调查流程识别异常交易活动。','ongoing transaction monitoring','How would we divide transaction monitoring responsibilities?'],
['Treasury','Treasury management','资金管理','Managing a company’s money and funding needs.','统筹现金、流动性、资金配置和相关风险。','treasury operations','How does your treasury team manage prefunding?'],
['Settlement','Settlement cycle','结算周期','The time needed to complete settlement.','从交易或指令发生到完成资金或资产交付的时间。','shorten the settlement cycle','What is the settlement cycle for this corridor?'],
['Clearing','Netting','净额结算计算','Offsetting obligations to calculate what is owed.','把多个应收应付义务抵销后计算净义务。','multilateral netting','Do you support netting before settlement?'],
['FX','FX spread','外汇买卖价差','The difference between currency buying and selling prices.','报价中的买卖价格差，可影响换汇总成本。','competitive FX spread','Does your quote include the FX spread?'],
['Liquidity','Prefunding','预先备付资金','Putting money in place before transactions happen.','提前在结算账户或合作方存入资金以支持支付。','prefunding requirements','Could we reduce the prefunding requirement during the pilot?'],
['Custody','Asset segregation','资产隔离','Keeping different owners’ assets separate.','通过账户或记录区分客户与自有资产；法律效果依安排而定。','segregate client assets','How are client assets segregated?'],
['Wallet','Private key','私钥','A secret used to authorize blockchain transactions.','控制签名权限的密码学信息，需要安全保管。','private key management','Who controls the private keys in this model?'],
['On-ramp / Off-ramp','Off-ramp','法币出金通道','Converting digital assets into fiat money.','把数字资产兑换并支付为法币的服务路径。','local off-ramp','Can you support local off-ramps for business customers?'],
['Cross-border payments','Payment corridor','支付走廊','A route between two markets for payments.','连接付款市场与收款市场的业务路径。','priority corridor','Which payment corridors are your priorities?'],
['Licensing','License scope','牌照范围','The activities a license allows.','许可涵盖的实体、业务、客户和地区边界。','within the license scope','Is this activity within your license scope?'],
['Partnership','Pilot program','试点项目','A limited test before a wider launch.','以限定范围、指标和期限验证合作可行性。','launch a pilot','Could we start with a pilot in one corridor?'],
['JV','Joint venture','合资企业／联合业务安排','A business created or run by partners together.','合作方共享投入、治理安排和经济利益的合作结构。','form a joint venture','What would each side contribute to the joint venture?'],
['Fundraising','Due diligence','尽职调查','Checking a business before a transaction.','评估财务、法律、技术和商业信息的调查过程。','conduct due diligence','What materials would you need for due diligence?'],
['Negotiation','Revenue share','收入分成','Dividing agreed revenue between partners.','基于约定收入定义、扣除项和周期分配收入。','revenue-sharing model','How would we define net revenue for the revenue share?']
];
export const terms=raw.map((r,i)=>({id:i,category:r[0],en:r[1],zh:r[2],simple:r[3],industry:r[4],collocations:r[5],example:r[6],meeting:'在讨论 '+r[0]+' 的职责、条件或下一步时，可以问：'+r[6]}));
export const roles=['支付公司 CEO','银行 BD','Stablecoin 发行方','Web3 公司','合规负责人','投资人','技术负责人','潜在 JV 合作方'];
export const scenes=['第一次见面','Coffee chat','Networking','项目介绍','正式会议','产品 Demo','商务合作','API 合作','银行合作','MOU','JV','Revenue Share','价格谈判','对方拒绝','对方压价','合规质疑','投资人 Pitch','Due Diligence'];
export const questions=['Which payment corridors are your priorities?','How do you currently handle settlement and liquidity?','What would a successful pilot look like?','Which customer segments do you focus on?','What does your onboarding process involve?','Which integrations would be required?','How should we divide compliance responsibilities?','What pricing model would work for you?','Who else should join our next discussion?','Can we agree on a timeline for next steps?'];
export const theirQuestions=['What problem are you solving?','Why would we partner with you rather than work directly with a stablecoin issuer?','Who are your target customers?','Which markets are you focusing on?','How does your business model work?','What would our responsibilities be?','How do you approach compliance?','What are your liquidity requirements?','How long would integration take?','What would you propose as a first step?'];
export const opening='Thank you for making the time. We’re building infrastructure that connects local payment networks with stablecoin settlement. I’d love to understand where you see opportunities for collaboration.';
export const expressions=['We’d like to explore a potential partnership with you.','Could you walk me through your current process?','What would a successful pilot look like for your team?','We’re open to discussing a structure that works for both sides.','Shall we agree on the next steps before we wrap up?'];
export const survival=['Airport','Immigration','Hotel','Taxi','Restaurant','Bank','Phone call','Appointment','Conference','Networking event','Social dinner','Emergency'];
export const survivalPhrases=['Where can I find the transfer desk?','I’m here for business meetings.','I have a reservation under my name.','Could you take me to this address, please?','Could I see the menu, please?','What documents do I need to open an account?','Could you repeat that more slowly, please?','Would tomorrow afternoon work for you?','Where is the registration desk?','What brings you to this event?','It’s been great getting to know you.','Please call the local emergency services.'];
