import {useState,useEffect,useRef} from 'react';
export const empty={words:{},mistakes:[],saved:[],history:[],done:{},meetings:[],plans:{},customTerms:[],skills:{},profile:{goal:'Stablecoin、Payments、Web3 与 JV 商务拓展',company:'',level:'需要提示',listening:'',minutes:35}};
export const uid=()=>crypto.randomUUID();
export const day=()=>new Date().toLocaleDateString('en-CA');
export async function api(path,options={}){const res=await fetch('/api/'+path,{...options,headers:{'content-type':'application/json',...options.headers}});let data;try{data=await res.json()}catch{throw new Error('服务暂不可用，请重试')}if(!res.ok){const e=new Error(data.error||'请求失败');e.status=res.status;throw e}return data}
export function useCloud(){const [state,set]=useState(empty),[status,Status]=useState('loading'),[error,Error]=useState(''),[ready,Ready]=useState(false);const live=useRef(empty),revision=useRef(0),pending=useRef(false),busy=useRef(false),loaded=useRef(false),stopped=useRef(false);async function load(force=false){if((pending.current||busy.current)&&!force)return;Status('loading');Error('');try{const r=await api('state');const value={...empty,...r.state,profile:{...empty.profile,...r.state?.profile}};revision.current=r.revision;live.current=value;set(value);loaded.current=true;Ready(true);stopped.current=false;pending.current=false;Status('saved')}catch(e){Status('error');Error(e.message)}}useEffect(()=>{load()},[]);
async function flush(){if(busy.current||!loaded.current||stopped.current)return;busy.current=true;while(pending.current){pending.current=false;const value=live.current;Status('saving');try{const r=await api('state',{method:'PUT',body:JSON.stringify({revision:revision.current,state:value})});revision.current=r.revision;Status('saved');Error('')}catch(e){pending.current=true;stopped.current=true;Status(e.status===409?'conflict':'error');Error(e.message);break}}busy.current=false}
function update(fn){if(!loaded.current)return;const n=typeof fn==='function'?fn(live.current):fn;live.current=n;set(n);pending.current=true;flush()}
function retry(){if(!loaded.current){load();return}stopped.current=false;flush()}
useEffect(()=>{function exit(e){if(pending.current||busy.current){e.preventDefault();e.returnValue=''}}window.addEventListener('beforeunload',exit);return()=>window.removeEventListener('beforeunload',exit)},[]);
return {state,update,status,error,load,retry,ready};}
export function download(state){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=u;a.download='Global-Copilot-Learning.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
